In [1]:
from sklearn import datasets
iris = datasets.load_iris()

In [2]:
print iris.DESCR


Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [3]:
print iris.data

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [4]:
print iris.data.shape

(150, 4)


In [6]:
print iris.feature_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
print iris.target 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [8]:
print iris.target.shape

(150,)


In [9]:
print iris.target_names


['setosa' 'versicolor' 'virginica']


In [10]:
print type(iris.data)

<type 'numpy.ndarray'>


In [11]:
import pandas as pd 
import numpy as np

In [12]:
colors = list()

In [13]:
palette = {0: 'red', 1: 'green', 2: 'blue'}

In [14]:
for c in np.nditer(iris.target): colors.append(palette[int(c)])
    #using the pallete dictionary we convert each numeric class into a color string 

In [15]:
dataframe = pd.DataFrame(iris.data, columns = iris.feature_names)

In [19]:
scatterplot = pd.scatter_matrix(dataframe, alpha = 0.3, figsize=(10,10), diagonal ='hist', color = colors,
                               grid=True)

# ML repository

In [20]:
from sklearn.datasets import fetch_mldata

In [21]:
earthquakes = fetch_mldata('global-earthquakes')

In [22]:
print earthquakes.data

[[  3.46098000e+04  -9.21000000e+00   1.50630000e+02   5.30000000e+00]
 [  5.22298000e+04  -1.50100000e+01  -1.73960000e+02   5.00000000e+00]
 [  1.14237500e+05  -3.55100000e+01  -1.62100000e+01   6.00000000e+00]
 ..., 
 [  2.55531500e+04  -3.35000000e+01  -7.21700000e+01   5.00000000e+00]
 [  8.54490000e+04  -3.54600000e+01  -7.28500000e+01   5.40000000e+00]
 [  9.30398300e+04   5.44700000e+01   1.10230000e+02   5.30000000e+00]]


In [24]:
print earthquakes.data.shape


(59209, 4)


# LIBSVM 

In [25]:
import urllib2

In [27]:
target_page ='http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/a1a'
a2a = urllib2.urlopen(target_page)


In [29]:
from sklearn.datasets import load_svmlight_file

In [30]:
X_train , y_train = load_svmlight_file(a2a)

In [31]:
print X_train.shape, y_train.shape

(1605, 119) (1605,)


## Loading data directly from CSV or text files

In [32]:
#/home/aryaveer/Desktop/Python_ML/Datasets
housing = np.loadtxt('/home/aryaveer/Desktop/Python_ML/Datasets/regression-datasets-housing.csv', delimiter =',')

In [33]:
print type(housing)

<type 'numpy.ndarray'>


In [34]:
print housing.shape

(506, 14)


In [35]:
import numpy as np 


In [36]:
type(np.loadtxt)

function

In [38]:
housing_int = np.loadtxt('/home/aryaveer/Desktop/Python_ML/Datasets/regression-datasets-housing.csv', delimiter =',',dtype=long)

In [39]:
print housing [0:3],'/n',housing_int[0:3]

[[  6.32000000e-03   1.80000000e+01   2.31000000e+00   0.00000000e+00
    5.38000000e-01   6.57500000e+00   6.52000000e+01   4.09000000e+00
    1.00000000e+00   2.96000000e+02   1.50000000e+01   3.96900000e+02
    4.98000000e+00   2.40000000e+01]
 [  2.73100000e-02   0.00000000e+00   7.07000000e+00   0.00000000e+00
    4.69000000e-01   6.42100000e+00   7.89000000e+01   4.96710000e+00
    2.00000000e+00   2.42000000e+02   1.70000000e+01   3.96900000e+02
    9.14000000e+00   2.16000000e+01]
 [  2.72900000e-02   0.00000000e+00   7.07000000e+00   0.00000000e+00
    4.69000000e-01   7.18500000e+00   6.11000000e+01   4.96710000e+00
    2.00000000e+00   2.42000000e+02   1.70000000e+01   3.92830000e+02
    4.03000000e+00   3.47000000e+01]] /n [[  0  18   2   0   0   6  65   4   1 296  15 396   4  24]
 [  0   0   7   0   0   6  78   4   2 242  17 396   9  21]
 [  0   0   7   0   0   7  61   4   2 242  17 392   4  34]]


In [40]:
iris_filename = '/home/aryaveer/Desktop/Python_ML/Datasets/datasets-uci-iris.csv'

In [42]:
iris = pd.read_csv(iris_filename, sep=',', decimal='.',
header=None, names= ['sepal_length', 'sepal_width', 'petal_length',
'petal_width', 'target'])

In [43]:
iris_data = iris.values[:,:4]

In [44]:
iris_target , iris_target_labels = pd.factorize(iris.target)

In [45]:
print iris_data.shape, iris_target.shape

(150, 4) (150,)
